import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Shared/Navbar";
import Footer from "./Shared/Footer";
import AuthProvider from "./lib/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "CK444",
  description: "Generated by Ahmed Ahiya",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <Navbar />
            {children}
          <Footer />
        </AuthProvider>

      </body>
    </html>
  );
}
